language: php

php:
  - 5.4
  - 5.5

before_script:
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - export NODE_PATH="$(pwd)/node_modules"
  - npm install -g less
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - sudo sed -i -e "s,/usr/local/nodejs-bin/lib/node_modules/,$(NODE_PATH)/,g" app/config/parameters.yml
  - make configure
  - make install
  #- npm install zombie@1.4.1
  - bin/behat

script:
  - phpcs --extensions=php -n --standard=PSR2 --report=full src

notifications:
  email:
    recipients:
      - "nbastien@prestaconcept.net"
      - "aflaus@prestaconcept.net"
