imports:
    - { resource: '../bundles/application/sonata_admin.yml' }
    - { resource: '../bundles/application/sonata_block.yml' }
    - { resource: '../bundles/application/sonata_media.yml' }
    - { resource: '../bundles/application/sonata_translation.yml' }
    - { resource: '../bundles/application/presta_sonata_admin_extended.yml' }
