imports:
    - { resource: '../bundles/sonata_admin.yml' }
    - { resource: '../bundles/sonata_block.yml' }
    - { resource: '../bundles/sonata_media.yml' }
    - { resource: '../bundles/sonata_translation.yml' }
    - { resource: '../bundles/presta_sonata_navigation.yml' }
    - { resource: '../bundles/presta_sonata_admin_extended.yml' }
