imports:
    - { resource: '@PrestaCMSCoreBundle/Resources/config/roles.yml' }
    - { resource: '@PrestaCMSCoreBundle/Resources/config/config.yml' }
    - { resource: '@PrestaCMSUserBundle/Resources/config/config.yml' }
    - { resource: '@PrestaCMSCKEditorBundle/Resources/config/config.yml' }
    - { resource: '@PrestaCMSSandboxBundle/Resources/config/config.yml' }
    - { resource: '../bundles/presta_cms_core.yml' }
    - { resource: '../bundles/presta_cms_contact.yml' }
    - { resource: '../bundles/presta_cms_social.yml' }
    - { resource: '../bundles/presta_cms_sitemap_bridge.yml' }
    - { resource: '../phpcr_doctrine_dbal.yml' }
    - { resource: '../bundles/doctrine_phpcr.yml' }
