imports:
    - { resource: '@PrestaSonataAdminExtendedBundle/Resources/config/config.yml' }
    - { resource: '@PrestaSonataAdminExtendedBundle/Resources/config/user/config.yml'}
    - { resource: '@PrestaSonataAdminExtendedBundle/Resources/config/user/config_navigation.yml' }
    #- { resource: '@PrestaSonataAdminExtendedBundle/Resources/config/user/config_dashboard.yml' }
    - { resource: '@PrestaSonataAdminExtendedBundle/Resources/config/media/config.yml'}
    - { resource: '@PrestaSonataAdminExtendedBundle/Resources/config/media/config_navigation.yml' }
    #- { resource: '@PrestaSonataAdminExtendedBundle/Resources/config/media/config_dashboard.yml' }
    - { resource: '@SonataTranslationBundle/Resources/config/config.yml'}

parameters:
    locale:  en
    locales: [fr, en, it, nl, es]
    presta_sonata_admin_extended.locales: [fr, en]
    presta_sonata_admin_extended.default_locale: en

assetic:
    bundles:
        - SonataAdminBundle
        - PrestaSonataAdminExtendedBundle
        - ApplicationSonataAdminBundle
        - PrestaComposerPublicBundle

sonata_admin:
    title:      ' '
    title_logo: ./bundles/prestasonataadminextended/img/logo_title.jpg
    templates:
        # default global templates
        layout:  ApplicationSonataAdminBundle::layout.html.twig
        user_block: PrestaSonataAdminExtendedBundle:Core:user_block.html.twig
#        dashboard:  PrestaSonataAdminExtendedBundle:Dashboard:two_columns.html.twig
#        list:    PrestaSonataAdminExtendedBundle:CRUD:list.html.twig
