presta_sonata_admin_extended:
    resource: "@PrestaSonataAdminExtendedBundle/Resources/config/routing.yml"
    prefix:   /

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

# Redirect if we have nothing in the front
sonata_admin_only:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /admin
        permanent: true
