PrestaSitemapBundle:
    resource: "@PrestaSitemapBundle/Resources/config/routing.yml"
    prefix:   /

# Presta Admin
presta_sonata_admin_extended:
    resource: "@PrestaSonataAdminExtendedBundle/Resources/config/routing.yml"
    prefix:   /

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

# PrestaCMS
PrestaCMSCoreBundle:
    resource: "@PrestaCMSCoreBundle/Resources/config/routing.xml"
    prefix:   /admin/{_locale}/

presta_cms_sandbox:
    resource: "@PrestaCMSSandboxBundle/Resources/config/routing.xml"
    prefix:   /

presta_cms_contact:
    resource: "@PrestaCMSContactBundle/Resources/config/routing.xml"
    prefix:   /

prestacms_user:
    resource: "@PrestaCMSUserBundle/Resources/config/routing.xml"
    prefix: /user

tree:
    resource: "@SonataDoctrinePHPCRAdminBundle/Resources/config/routing/tree.xml"
