assetic:
    bundles:
        - SonataAdminBundle
        - PrestaSonataAdminExtendedBundle
        - ApplicationSonataAdminBundle
        - ApplicationPrestaCMSCoreBundle
        - PrestaCMSCoreBundle
        - PrestaComposerPublicBundle
        - PrestaCMSThemeBasicBundle
