imports:
    - { resource: '@SonataTranslationBundle/Resources/config/config.yml'}

sonata_translation:
    locales: [fr, en]
    default_locale: fr
    gedmo:
        enabled: true
    phpcr:
        enabled: true
